apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
        name: guestbook
        env: dev
      - cluster: engineering-prod
        url: https://kubernetes.default.svc
        name: guestbook
        env: dev
  template:
    metadata:
      name: '{{name}}-{{cluster}}'
    spec:
      project: project001
      source:
        repoURL: https://github.com/argoproj/applicationset.git
        targetRevision: HEAD
        path: overlays/{{env}}/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: project001
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
