---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: myproject
  source:
    path: deploy/kubernetes
    repoURL: https://github.com/Tomelin/argocd-backstage.git
    targetRevision: HEAD
    kustomize:
      version: "v4.5.7 2022-08-02T16:35:54Z"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
